name: Flutter CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code
      - uses: actions/checkout@v3

      # 2. Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.5'  

      - run: flutter clean

      # 3. Get dependencies
      - run: flutter pub get

      # 4. Analyze (Lint check)
      - run: flutter analyze

      # 5. Run tests
      - run: flutter test
